name: CI Pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
    paths:
      - 'rdicidr-0.1.0/**'

jobs:
  ci:
    name: Full CI Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '15' # or whatever version is in .nvmrc or package.json

      - name: Install dependencies
        run: npm install
        working-directory: rdicidr-0.1.0

      - name: Run Linter (ESLint)
        run: npm run lint
        working-directory: rdicidr-0.1.0

      - name: Run Formatter (Prettier)
        run: npm run prettier -- --write
        working-directory: rdicidr-0.1.0

      - name: Run Tests (Jest)
        env: 
          CI: true
        run: npm run test
        working-directory: rdicidr-0.1.0

      - name: Build Application
        run: npm run build
        working-directory: rdicidr-0.1.0
