name: Node.js CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      working-directory: rdicidr-0.1.0

    - name: Run linter
      run: npm run lint
      working-directory: rdicidr-0.1.0

    - name: Run formatter
      run: npm run prettier
      working-directory: rdicidr-0.1.0

    - name: Run tests
      env: 
        CI: true
      run: npm run test
      working-directory: rdicidr-0.1.0

    - name: Build project
      run: npm run build
      working-directory: rdicidr-0.1.0
    